apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
  namespace: cicd-demo
  labels:
    app: fastapi-demo
    managed-by: jenkins
spec:
  type: NodePort
  selector:
    app: fastapi-demo
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  sessionAffinity: None
